#Pandas Answers

##1. Basic Exploration

In [ ]:
import pandas as pd

df = pd.read_csv('/content/auto-mpg.csv')

df.head(10)

df.shape

df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

##2. Filtering and Indexing

In [ ]:
df[(df['model year'] == 75) & (df['weight'] < 3000)][['car name', 'weight', 'mpg']]

              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

##3. Handling Missing Data

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [ ]:
#converting horsepower to numeric
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

In [ ]:
# Fill missing values with median
median_hp = df['horsepower'].median()
df.fillna({'horsepower': median_hp}, inplace=True)

df['horsepower'].head()

0    130.0
1    165.0
2    150.0
3    150.0
4    140.0
Name: horsepower, dtype: float64

##4. Data Transformation

In [ ]:
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']
df['power_to_weight_ratio']

0      0.037100
1      0.044679
2      0.043655
3      0.043694
4      0.040591
         ...
393    0.030824
394    0.024413
395    0.036601
396    0.030095
397    0.030147
Name: power_to_weight_ratio, Length: 398, dtype: float64

##5. Group By

In [ ]:
origin_groups = df.groupby('origin')
origin_groups['mpg'].mean()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

##6. Sorting

In [ ]:
df.sort_values(by='mpg', ascending=False).head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,power_to_weight_ratio
322,46.6,4,86.0,65.0,2110,17.9,80,3,mazda glc,0.030806
329,44.6,4,91.0,67.0,1850,13.8,80,3,honda civic 1500 gl,0.036216
325,44.3,4,90.0,48.0,2085,21.7,80,2,vw rabbit c (diesel),0.023022
394,44.0,4,97.0,52.0,2130,24.6,82,2,vw pickup,0.024413
326,43.4,4,90.0,48.0,2335,23.7,80,2,vw dasher (diesel),0.020557
244,43.1,4,90.0,48.0,1985,21.5,78,2,volkswagen rabbit custom diesel,0.024181
309,41.5,4,98.0,76.0,2144,14.7,80,2,vw rabbit,0.035448
330,40.9,4,85.0,93.5,1835,17.3,80,2,renault lecar deluxe,0.050954
324,40.8,4,85.0,65.0,2110,19.2,80,3,datsun 210,0.030806
247,39.4,4,85.0,70.0,2070,18.6,78,3,datsun b210 gx,0.033816

##Apply function

###7. Apply this function to each row and store the result in the new column

In [ ]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1)
df['performance_score']

0      0.061644
1      0.046710
2      0.057625
3      0.055928
4      0.051754
         ...
393    0.150968
394    0.508169
395    0.161743
396    0.198400
397    0.221103
Name: performance_score, Length: 398, dtype: float64

###8. Visualization Preparation

In [ ]:
df.groupby('model year')[['mpg', 'weight', 'horsepower']].mean()

                  mpg       weight  horsepower
model year
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

###9. Exporting Data

In [ ]:
df[df['mpg'] > 30][['mpg','cylinders','horsepower','weight']].to_csv('high_mpg_cars.csv', index=False)

###10. Finding Anomalies (IQR)

In [ ]:
#Calculate the IQR for mpg
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1

# Define outliers as values less than
#Q1 - 1.5 * IQR or greater than Q3 +1.5 * IQR.

outliers = df[(df['mpg'] < (Q1 - 1.5 * IQR)) | (df['mpg'] > (Q3 + 1.5 * IQR))]

#Create a DataFrame of cars classified as outliers,
#displaying car_name, mpg,and model_year.

outliers[['car name', 'mpg', 'model year']]

      car name   mpg  model year
322  mazda glc  46.6          80

#Numpy Answers

In [ ]:
import numpy as np

###1. Basic Array Operations

In [ ]:
mpg = df['mpg'].values

np.mean(mpg)
np.median(mpg)
np.std(mpg)

np.sum(mpg > 25)

print(f"Mean: {np.mean(mpg):.2f}")
print(f"Median: {np.median(mpg):.2f}")
print(f"Std Dev: {np.std(mpg):.2f}")
print(f"Count > 25 mpg: {np.sum(mpg > 25)}")

Mean: 23.51
Median: 23.00
Std Dev: 7.81
Count > 25 mpg: 158

###2. Filtering

In [ ]:
cars = df['car name'].values
cyl = df['cylinders'].values

cars[cyl > 6].tolist()

['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brougham',
 'chevrolet caprice classic',
 'ford ltd',
 'plymouth fury gran sedan',
 'chrysler new yorker brougham',
 'buick electra 225 custom',
 'amc ambassador brougham',
 'chevrolet impala',
 'ford country',
 'plymouth custom suburb',
 'oldsmobile vista cruiser',
 'chevrolet monte carlo s',
 'pontiac grand prix',
 'dodge dart custom',
 'oldsmobile omega',
 'ford gran torino',
 'buick century luxus (sw)',
 'dodge coronet custom (sw)',
 'ford gran torino (sw)',
 'amc matador (sw)',
 'pontiac catalina',
 'chevrolet bel air',
 'plymouth grand fury',
 'ford ltd',
 'chevrolet monza 2+2',
 'ford mustang ii',
 'chevrolet chevelle malibu classic',
 'dodge coronet brougham',
 'amc matador',
 'ford gran torino',
 'plymouth volare premier v8',
 'cadillac seville',
 'chevy c10',
 'ford f108',
 'dodge d100',
 'chevrolet caprice classic',
 'oldsmobile cutlass supreme',
 'dodge monaco brougham',
 'mercury cougar brougham',
 'pontiac grand prix lj',
 'chevrolet monte carlo landau',
 'chrysler cordoba',
 'ford thunderbird',
 'oldsmobile cutlass salon brougham',
 'dodge diplomat',
 'mercury monarch ghia',
 'chevrolet monte carlo landau',
 'ford futura',
 'dodge magnum xe',
 'chevrolet caprice classic',
 'ford ltd landau',
 'mercury grand marquis',
 'dodge st. regis',
 'buick estate wagon (sw)',
 'ford country squire (sw)',
 'chevrolet malibu classic (sw)',
 'chrysler lebaron town @ country (sw)',
 'cadillac eldorado',
 'oldsmobile cutlass salon brougham',
 'oldsmobile cutlass ls']

###3. Percentiles

In [ ]:
weight = df['weight'].values

np.percentile(weight, [25, 50, 75])

array([2223.75, 2803.5 , 3608.  ])

###4.Array Manipulation

In [ ]:
acc = df['acceleration'].values

# normalization (min-max scaling)
norm_acc = (acc - acc.min()) / (acc.max() - acc.min())

print(norm_acc)

[0.23809524 0.20833333 0.17857143 0.23809524 0.14880952 0.11904762
 0.05952381 0.0297619  0.11904762 0.0297619  0.11904762 0.
 0.08928571 0.11904762 0.41666667 0.44642857 0.44642857 0.47619048
 0.38690476 0.74404762 0.56547619 0.38690476 0.56547619 0.26785714
 0.41666667 0.35714286 0.41666667 0.32738095 0.625      0.38690476
 0.44642857 0.35714286 0.6547619  0.29761905 0.44642857 0.44642857
 0.44642857 0.44642857 0.23809524 0.20833333 0.32738095 0.29761905
 0.20833333 0.23809524 0.23809524 0.32738095 0.6547619  0.41666667
 0.38690476 0.35714286 0.35714286 0.68452381 0.38690476 0.6547619
 0.5952381  0.6547619  0.74404762 0.44642857 0.53571429 0.92261905
 0.68452381 0.50595238 0.23809524 0.23809524 0.32738095 0.29761905
 0.20833333 0.17857143 0.32738095 0.32738095 0.26785714 0.32738095
 0.26785714 0.35714286 0.47619048 0.35714286 0.38690476 0.5952381
 0.68452381 0.5952381  0.47619048 0.53571429 0.38690476 0.41666667
 0.50595238 0.29761905 0.20833333 0.29761905 0.38690476 0.26785714
 0.20833333 0.23809524 0.29761905 0.38690476 0.17857143 0.17857143
 0.17857143 0.50595238 0.5952381  0.47619048 0.50595238 0.47619048
 0.77380952 0.35714286 0.26785714 0.29761905 0.26785714 0.41666667
 0.6547619  0.68452381 0.50595238 0.32738095 0.625      0.35714286
 0.44642857 0.29761905 0.08928571 0.68452381 0.44642857 0.35714286
 0.44642857 0.17857143 0.35714286 0.32738095 0.17857143 0.50595238
 0.53571429 0.47619048 0.53571429 0.6547619  0.50595238 0.77380952
 0.53571429 0.53571429 0.5952381  0.50595238 0.35714286 0.38690476
 0.32738095 0.47619048 0.44642857 0.50595238 0.44642857 0.38690476
 0.50595238 0.6547619  0.38690476 0.44642857 0.35714286 0.41666667
 0.44642857 0.47619048 0.47619048 0.47619048 0.77380952 0.68452381
 0.20833333 0.35714286 0.38690476 0.32738095 0.77380952 0.625
 0.6547619  0.6547619  0.41666667 0.32738095 0.23809524 0.47619048
 0.53571429 0.47619048 0.625      0.32738095 0.50595238 0.53571429
 0.38690476 0.35714286 0.53571429 0.41666667 0.53571429 0.38690476
 0.32738095 0.56547619 0.44642857 0.5297619  0.41071429 0.57738095
 0.43452381 0.29761905 0.29761905 0.35119048 0.28571429 0.44047619
 0.38690476 0.57142857 0.57142857 0.8452381  0.83928571 0.36904762
 0.55952381 0.57738095 0.77380952 0.48809524 0.58333333 0.25
 0.53571429 0.5        0.33333333 0.45833333 0.30952381 0.82738095
 0.44642857 0.51785714 0.24404762 0.23809524 0.41666667 0.35714286
 0.625      0.4047619  0.63095238 0.44642857 0.52380952 0.26785714
 0.6547619  0.33928571 0.41071429 0.5        0.5297619  0.57738095
 0.6547619  0.18452381 0.20238095 0.25       0.38690476 0.38690476
 0.47619048 0.60714286 0.46428571 0.53571429 0.4702381  0.5
 0.36309524 0.38690476 0.28571429 0.32738095 0.80357143 0.38095238
 0.67857143 0.63095238 0.5        0.44642857 0.30952381 0.28571429
 0.66666667 0.60714286 0.46428571 0.44047619 0.54761905 0.54761905
 0.46428571 0.51785714 0.63690476 0.42261905 0.30952381 0.32142857
 0.19047619 0.33928571 0.50595238 0.36904762 0.39880952 0.38690476
 0.4047619  0.51785714 0.57142857 0.41071429 0.4702381  0.33333333
 0.45833333 0.46428571 0.41071429 0.51190476 0.44047619 0.60714286
 0.55357143 0.60714286 0.51190476 0.44047619 0.32142857 0.30952381
 0.42857143 0.41071429 0.375      0.41666667 0.29761905 0.35714286
 0.42857143 0.38095238 0.41666667 0.7202381  0.55952381 1.
 0.8452381  0.30952381 0.41071429 0.66666667 0.39880952 0.47619048
 0.19642857 0.29166667 0.30952381 0.39880952 0.64285714 0.44642857
 0.5        0.50595238 0.60119048 0.7202381  0.63690476 0.46428571
 0.44642857 0.56547619 0.41666667 0.42857143 0.58928571 0.38095238
 0.66666667 0.81547619 0.93452381 0.70833333 0.82142857 0.3452381
 0.55357143 0.5952381  0.43452381 0.20238095 0.26785714 0.42261905
 0.375      0.53571429 0.45833333 0.5        0.38095238 0.27380952
 0.29166667 0.5297619  0.5        0.48214286 0.58333333 0.67857143
 0.55357143 0.47619048 0.41071429 0.48809524 0.75595238 0.36904762
 0.46428571 0.38095238 0.52380952 0.4047619  0.61309524 0.73809524
 0.69047619 0.27380952 0.3452381  0.46428571 0.6547619  0.54166667
 0.51190476 0.69047619 0.63095238 0.5952381  0.48809524 0.47619048
 0.5952381  0.5        0.74404762 0.43452381 0.60714286 0.57142857
 0.39880952 0.55357143 0.38690476 0.38690476 0.5297619  0.41666667
 0.45833333 0.48809524 0.5        0.53571429 0.38690476 0.39880952
 0.35119048 0.29761905 0.55357143 0.45238095 0.98809524 0.21428571
 0.63095238 0.67857143]

###5. Broadcasting

In [ ]:
hp = df['horsepower'].values

# replace NaN
hp = np.where(np.isnan(hp), np.nanmean(hp), hp)

hp_new = hp * 1.1
print(hp_new[:10])

[143.  181.5 165.  165.  154.  217.8 242.  236.5 247.5 209. ]

###6. Boolean Indexing

In [ ]:
# Convert columns to NumPy arrays
origin = df['origin'].values
displacement = df['displacement'].values

# Select only cars from Europe (origin == 2)
europe_disp = displacement[origin == 2]

# Calculate average
avg_disp = np.mean(europe_disp)

print(avg_disp)

109.14285714285714

###7. Matrix Operations

In [ ]:
matrix = df[['mpg','horsepower','weight']].values
vector = np.array([1, 0.5, -0.2])

np.dot(matrix, vector)

array([-617.8 , -641.1 , -594.2 , -595.6 , -602.8 , -754.2 , -746.8 ,
       -740.9 , -758.5 , -660.  , -612.6 , -627.8 , -662.2 , -490.7 ,
       -402.9 , -497.1 , -488.3 , -453.9 , -355.  , -318.  , -465.9 ,
       -417.  , -402.5 , -364.3 , -463.6 , -805.5 , -765.2 , -760.4 ,
       -840.9 , -355.  , -379.8 , -373.1 , -337.45, -457.8 , -619.3 ,
       -598.8 , -597.4 , -589.6 , -745.3 , -791.3 , -740.3 , -730.2 ,
       -889.  , -851.2 , -927.5 , -519.4 , -423.6 , -587.4 , -565.8 ,
       -378.  , -351.6 , -349.8 , -345.  , -291.1 , -253.1 , -309.8 ,
       -330.  , -384.1 , -360.2 , -400.8 , -416.6 , -381.2 , -759.3 ,
       -775.5 , -737.  , -735.3 , -642.4 , -811.6 , -809.9 , -799.2 ,
       -776.4 , -398.5 , -688.4 , -741.6 , -775.8 , -726.4 , -512.6 ,
       -442.2 , -531.3 , -377.3 , -414.  , -383.6 , -429.7 , -364.8 ,
       -349.  , -719.5 , -645.4 , -712.1 , -725.9 , -665.4 , -879.4 ,
       -804.8 , -780.6 , -758.4 , -826.5 , -865.7 , -663.7 , -553.7 ,
       -589.6 , -521.  , -542.2 , -510.3 , -341.  , -913.4 , -885.7 ,
       -832.8 , -797.8 , -489.8 , -391.8 , -423.2 , -406.8 , -361.8 ,
       -400.5 , -419.9 , -382.  , -728.9 , -724.6 , -319.9 , -370.1 ,
       -450.9 , -498.6 , -589.8 , -453.  , -480.4 , -631.8 , -552.9 ,
       -507.25, -511.2 , -602.2 , -325.5 , -424.2 , -302.7 , -445.9 ,
       -690.2 , -655.4 , -652.1 , -742.2 , -851.8 , -802.4 , -843.6 ,
       -762.4 , -373.3 , -333.1 , -395.  , -272.8 , -338.1 , -359.5 ,
       -360.1 , -385.7 , -425.3 , -405.7 , -335.5 , -586.3 , -621.3 ,
       -635.4 , -580.6 , -832.6 , -800.5 , -808.6 , -843.4 , -709.4 ,
       -710.9 , -676.  , -691.5 , -531.8 , -569.2 , -556.3 , -367.7 ,
       -463.3 , -512.8 , -456.4 , -468.4 , -384.1 , -436.5 , -530.3 ,
       -323.4 , -578.2 , -468.3 , -524.4 , -518.  , -451.7 , -299.5 ,
       -421.8 , -378.5 , -443.4 , -385.5 , -371.9 , -755.5 , -747.  ,
       -716.9 , -752.5 , -574.6 , -596.1 , -537.9 , -549.5 , -352.  ,
       -378.3 , -323.4 , -299.5 , -660.2 , -657.8 , -655.5 , -573.6 ,
       -300.  , -331.  , -365.5 , -450.5 , -559.  , -700.  , -591.  ,
       -513.  , -687.5 , -769.5 , -725.5 , -696.  , -663.  , -343.5 ,
       -361.  , -300.  , -386.5 , -320.5 , -686.  , -740.  , -740.  ,
       -779.  , -631.5 , -612.  , -657.  , -637.5 , -738.  , -732.5 ,
       -754.5 , -776.5 , -320.  , -479.5 , -389.5 , -481.  , -348.2 ,
       -340.  , -333.5 , -368.5 , -492.5 , -443.5 , -467.5 , -329.9 ,
       -290.9 , -338.2 , -339.6 , -293.9 , -598.1 , -657.6 , -624.3 ,
       -635.3 , -563.  , -530.3 , -474.9 , -615.5 , -577.6 , -602.9 ,
       -550.7 , -650.4 , -603.9 , -593.3 , -588.8 , -553.4 , -728.5 ,
       -367.  , -437.  , -384.3 , -377.6 , -434.4 , -473.3 , -504.7 ,
       -408.6 , -494.2 , -548.5 , -479.9 , -599.3 , -331.  , -363.5 ,
       -570.  , -535.7 , -511.7 , -587.8 , -596.4 , -686.  , -662.9 ,
       -705.5 , -680.3 , -777.6 , -724.3 , -639.3 , -694.5 , -317.6 ,
       -328.4 , -307.3 , -466.6 , -642.1 , -694.5 , -575.3 , -615.1 ,
       -370.8 , -360.5 , -339.7 , -354.2 , -460.6 , -432.7 , -455.7 ,
       -432.7 , -349.3 , -325.5 , -356.9 , -334.1 , -462.6 , -503.6 ,
       -531.3 , -612.1 , -364.3 , -467.4 , -439.6 , -403.8 , -383.3 ,
       -342.9 , -479.6 , -348.7 , -348.7 , -399.6 , -520.1 , -586.5 ,
       -291.9 , -279.35, -361.7 , -308.2 , -483.3 , -410.3 , -421.  ,
       -510.65, -389.6 , -428.8 , -458.4 , -452.2 , -466.5 , -405.  ,
       -282.9 , -304.  , -286.9 , -347.2 , -325.5 , -341.3 , -328.9 ,
       -376.8 , -342.1 , -413.6 , -368.  , -382.75, -370.8 , -400.1 ,
       -440.1 , -458.4 , -577.9 , -563.3 , -496.6 , -501.8 , -605.6 ,
       -665.9 , -547.8 , -632.9 , -449.  , -457.  , -401.  , -441.5 ,
       -434.  , -475.  , -503.  , -537.25, -323.  , -334.  , -329.  ,
       -355.5 , -354.  , -352.  , -367.5 , -380.  , -321.5 , -327.5 ,
       -327.5 , -509.  , -522.5 , -445.  , -489.  , -453.  , -396.  ,
       -518.  , -488.  , -356.  , -385.  , -457.5 , -472.  ])

###8. Sorting

In [ ]:
sorted_idx = np.argsort(df['model year'].values)[::-1]

df['car name'].values[sorted_idx][:5]

array(['dodge aries se', 'pontiac phoenix', 'pontiac j2000 se hatchback',
       'chevrolet cavalier 2-door', 'chevrolet cavalier wagon'],
      dtype=object)

###9. Correlation

In [ ]:
mpg = df['mpg'].values
weight = df['weight'].values

np.corrcoef(mpg, weight)

array([[ 1.        , -0.83174093],
       [-0.83174093,  1.        ]])

###10. Conditional Aggregates

In [ ]:
cyl = df['cylinders'].values
mpg = df['mpg'].values

for c in np.unique(cyl):
    print(c, np.mean(mpg[cyl == c]))

3 20.55
4 29.28676470588235
5 27.366666666666664
6 19.985714285714284
8 14.963106796116506